# Generated by Django 3.2.2 on 2022-02-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Name', models.CharField(max_length=50)),
                ('Speed', models.IntegerField(max_length=3)),
                ('Average_Speed', models.IntegerField(max_length=3)),
                ('Temperature', models.IntegerField(max_length=3)),
                ('Fuel_level', models.CharField(max_length=10)),
                ('Engine_Status', models.CharField(max_length=20)),
            ],
        ),
    ]
